set PRJ_NAME colordetect.prj
set ACC_NAME color_detect
set CPP_DESIGN_TOP xf_colordetect_accel.cpp
set CPP_DESIGN_TB xf_colordetect_tb.cpp
set XPART xczu9eg-ffvb1156-2-e
set CSIM 0
set CSYNTH 1
set COSIM 0
set VIVADO_SYN 0
set VIVADO_IMPL 0
set VITIS_LIB_INCLUDE "/home/gbellocchi/workspace_tools/vitis/PYNQ_Composable_Pipeline/Vitis_Libraries/vision/L1/include"
set XF_PROJ_ROOT "/home/gbellocchi/workspace_tools/vitis/PYNQ_Composable_Pipeline/Vitis_Libraries/vision"
set OPENCV_INCLUDE "/home/gbellocchi/workspace_tools/opencv/opencv/build/include"
set OPENCV_LIB "/home/gbellocchi/workspace_tools/opencv/opencv/build/lib"
set CUR_DIR "/home/gbellocchi/workspace_tools/vitis/richie-arov-hls-use-case/L3/colordetect"
