# ------------------------------------------------------------------- #
# 	Author:      Gianluca Bellocchi <gianluca.bellocchi@unimore.it>   #
# ------------------------------------------------------------------- #

ROOT := $(patsubst %/,%, $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

CSRCS = main.c

-include $(HERO_OV_OPENMP_TESTS)/common/default.mk
